## Basic Configuration
baseurl = "https://robotenique.github.io/"
languageCode = "en"

title = "Juliano Garcia"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-188016442-1"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Juliano Garcia"
    title = "Robotenique's Home"
    description = "Data & Computer Scientist. Digressions about statistics, technology or anything else that comes in my mind. Opinions are my own."
    authorimage = "/img/me.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

    # Reverse the layout
    layoutreverse = true

    # Theme Color
    themecolor="theme-base-08"

    # Sidebar content at the bottom
    sidebarSticky = true

## Social Accounts
[params.social]
    github = "robotenique"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "juliano-garcia-oliveira"
    #twitter = "<username>"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "julianogarcia_1997@hotmail.com"
    #gravatar = "julianogarcia_1997@hotmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Projects"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 300
    url = "/about/"
